### ISSUE TITLE
ModuleNotFoundError: No module named 'perceval.backend'

### ISSUE THREAD

**Issue by sduenas** [chaoss/grimoirelab-perceval-gitee#1]
This error is raised when the backend is used with perceval because it doesn't follows the [PEP 420](https://peps.python.org/pep-0420/) about namespaces.

```
    from perceval.backend import find_signature_parameters, Archive
ModuleNotFoundError: No module named 'perceval.backend'
```

To fix it, you should remove `__init__.py` files of `perceval` and `perceval.backends` packages.

**Comment by shanchenqi** [comment]
Hi, @sduenas . Thanks for your help. I updated the code for this issue in https://github.com/chaoss/grimoirelab-perceval-gitee/pull/3. Could you help me to review it? If there is no problem, you could merge it directly.

**Comment by lbergmans** [comment]
Hi, I am trying to install grimoire-lab, and ran into the following issue:
```
  File "/Users/lodewijk/git/grimoirelab_dev/sources/grimoirelab-elk/grimoire_elk/elk.py", line 32, in <module>
    from perceval.backend import find_signature_parameters   #ModuleNotFoundError
ModuleNotFoundError: No module named 'perceval.backend'
```
With help of a colleague (I am a Python newbie), I figured out that `__init__.p` was missing, and indeed that resolved the issue!

But now, *with* the  `__init__.p`, of course I run into the issue above... 
```
  File "/Users/lodewijk/git/grimoirelab_dev/sources/grimoirelab-elk/grimoire_elk/utils.py", line 67, in <module>
    from perceval.backends.puppet.puppetforge import PuppetForge, PuppetForgeCommand
ModuleNotFoundError: No module named 'perceval.backends.puppet'
```
So, it seems a catch-22: any means to avoid this problem??

Related, I wonder whether a _clean_ installation of grimoirelab is tested regularly? I am running into quite a few obstacles..
